import './globals.css';
import type { Metadata } from 'next';
import { Inter, Ballet, Ubuntu } from 'next/font/google';
import { clsx } from 'clsx';

const inter = Inter({ subsets: ['latin'] });

export const ubuntu = Ubuntu({
	subsets: ['latin'],
	weight: ['400'],
});

// export const metadata: Metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app',
// };

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="fr">
			<body className={clsx(inter.className, 'bg-black text-slate-50')}>
				{children}
			</body>
		</html>
	);
}
