import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { clsx } from 'clsx';
import ContextProvider from '@/context/ContextProvider';
import { Header } from './Header/Header';
import { Home } from './Home/Home';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="fr">
			<body
				className={clsx(
					inter.className,
					'bg-black text-slate-50 overflow-x-hidden'
				)}
			>
				<ContextProvider>
					<Header />
					<Home />
				</ContextProvider>
			</body>
		</html>
	);
}
