import '../styles/globals.css';
import type { Metadata } from 'next';
import { Roboto, Montserrat } from 'next/font/google';
import { clsx } from 'clsx';
import ContextProvider from '@/context/ContextProvider';

const roboto = Roboto({
	subsets: ['latin'],
	weight: ['400', '700'],
	variable: '--font-roboto',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const monstserrat = Montserrat({
	subsets: ['latin'],
	weight: ['400', '700'],
	variable: '--font-montserrat',
});

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="fr">
			<body
				className={clsx(
					monstserrat.className,
					roboto.className,
					'bg-black text-slate-50 overflow-x-hidden'
				)}
			>
				<ContextProvider>{children}</ContextProvider>
			</body>
		</html>
	);
}
